rnorm(100)
my_rn<-rnorm(100)
mean(my_rn)
sd(my_rn)
my_rn+5
mean(my_rn+5)
speakers<-sample(c(1:25))
speakers
speakers<-sample(c(1:25),3)
speakers
speakers<-sample(c(1:25),3)
speakers
speakers<-sample(c(1:25),3)
speakers<-sample(c(1:25))
day1<-speakers[1:13]
day2<-speakers[14:25]
day1
rep("A",10)
my_rn[sd(my_rn)>1]
my_rn[c(sd(my_rn)>1)]
sd(my_rn)>1
my_rn>(mean(my_rn)-sd(my_rn))
my_rn[my_rn>(mean(my_rn)-sd(my_rn))]
my_rn.onesd<-my_rn[my_rn>(mean(my_rn)-sd(my_rn))]
hist(my_rn)
abline(v= c((mean(my_rn)-sd(my_rn)),(mean(my_rn)+sd(my_rn))),col= c(2,3))
